/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as ReviewCardIdRouteImport } from './routes/review/$cardId'
import { Route as ProjectIdRouteImport } from './routes/project/$id'

const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewCardIdRoute = ReviewCardIdRouteImport.update({
  id: '/review/$cardId',
  path: '/review/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/project/$id': typeof ProjectIdRoute
  '/review/$cardId': typeof ReviewCardIdRoute
  '/project/': typeof ProjectIndexRoute
}
export interface FileRoutesByTo {
  '/project/$id': typeof ProjectIdRoute
  '/review/$cardId': typeof ReviewCardIdRoute
  '/project': typeof ProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/project/$id': typeof ProjectIdRoute
  '/review/$cardId': typeof ReviewCardIdRoute
  '/project/': typeof ProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/project/$id' | '/review/$cardId' | '/project/'
  fileRoutesByTo: FileRoutesByTo
  to: '/project/$id' | '/review/$cardId' | '/project'
  id: '__root__' | '/project/$id' | '/review/$cardId' | '/project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProjectIdRoute: typeof ProjectIdRoute
  ReviewCardIdRoute: typeof ReviewCardIdRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$cardId': {
      id: '/review/$cardId'
      path: '/review/$cardId'
      fullPath: '/review/$cardId'
      preLoaderRoute: typeof ReviewCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ProjectIdRoute: ProjectIdRoute,
  ReviewCardIdRoute: ReviewCardIdRoute,
  ProjectIndexRoute: ProjectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
